# Generated by Django 4.1.2 on 2022-10-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
