# Generated by Django 4.1.2 on 2022-10-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
